Ability to disable manage_service if installed from package
voxpupuli/puppet-prometheus pull request #102
Opened 2017-11-02 12:59 UTC by Samgarr

2017-11-02 13:27 UTC, bastelfreak commented
@Samgarr thanks for the PR. @tuxmea what do you think about this solution? I would prefer it over https://github.com/voxpupuli/puppet-prometheus/pull/100

2017-11-02 13:56 UTC, tuxmea commented
I would recommend spec tests also for the new parameter. Besides this: looks nicer than mine.

2017-11-02 13:58 UTC, tuxmea requested changes

2017-11-02 13:58 UTC, tuxmea commented on manifests/daemon.pp
> +  $manage_service     = $::prometheus::params::manage_service,
The parameter should be taken from $::prometheus::manage_service ! Not taking default from params.pp

2017-11-02 13:59 UTC, tuxmea requested changes

2017-11-02 13:59 UTC, tuxmea commented on manifests/config.pp
>      # the vast majority of files here are init-files
This ssems to be an outdated version of config.pp. please rebase!

2019-05-11 15:40 UTC, bastelfreak commented
Hi @Samgarr, could you please rebase this again?

2019-05-12 10:35 UTC, Samgarr commented
Hi, i could rebase, but isn't this issue already solved?

2019-05-20 18:50 UTC, bastelfreak commented
Ah true, we now have a `manage_service` parameter

2019-05-20 18:50 UTC, closed without merging