remove dependency on camptocamp/systemd
voxpupuli/puppet-prometheus pull request #446
Opened 2020-04-22 18:14 UTC by juliantaylor

the camptocamp systemd module which is incompatible with other module
like eyp/systemd

note this was already discussed in https://github.com/voxpupuli/puppet-prometheus/pull/90 a while ago.
But even after these many years the systemd module usage here is still as minimal as it was before so I though I try to get the usage removed to allow the prometheus module to be used by more environments without a fork.

2020-04-24 21:39 UTC, bastelfreak commented
Hi,
the camptocamp/systemd module is used across all Vox Pupuli modules and it's the approved module for systemd on the forge. Based on that I think it's still fine to depend on that. To maintain our >130 modules, we need to keep our coding style as consistent as possible across all modules.  That's why we try to use the camptocamp module for all service files, drop_ins and resource/security limits.
Based on that: if we switch back to flat templates (which is IMO bad) we should do it in all modules.

I know that Puppet is very bad in handling namespaces and also bad in consolidating modules for the same approach. To be fair, that's also not an easy task. It's possible to implement support for several different systemd modules. People already did that in the past. I'm fine with reviewing and merging such a PR, but I don't think that dropping camptocamp/systemd is the way to go.

I will leave this PR open in case you or one from @voxpupuli/collaborators wants to respond and has a different point of view.

2020-04-24 21:57 UTC, juliantaylor commented
I don't see how consistent coding style is relevant if your usage of the systemd is a wrapper around the builtin file resource.
If it would be a module with more features like eyplib systemd which abstracts the stuff like the daemon-reload or the different systemd feature sets it would be more convincing argument but not really how it is used in this module.

It may make sense in other modules where the systemd usage is more complex and the module brings advantages, but not in this one. You have file resource usage for all the other init systems. I don't see why systemd needs to be treated specially in a less compatible way for no apparent benefit.

2020-04-24 22:07 UTC, juliantaylor commented
The tests do fail and the code can be cleaned up a bit with puppets new 6.1 systemd features, this MR is for now just probing the waters again by showing what the change would actually involve. Should you want to consider it I'll clean it up and fix the tests.

2020-04-24 22:28 UTC, ekohl requested changes

2020-04-24 22:28 UTC, ekohl commented on manifests/config.pp
> +        refreshonly => true,
You don't notify this resource so you are introducing a bug here. That's sort of the point of using a module to do so: you abstract away resources so you don't repeat yourself and introduce bugs.

Once we drop support for Puppet < 6.1.0 (which will be in November), then I'd agree there's not really any value.

2020-04-24 22:56 UTC, anarcat requested changes
i am not sure i see the point of this either. the systemd module is the standard one on the forge and i don't see what the proposed changes bring us. 

surely there is a way to have the systemd modules use a common API. it would certainly be simpler than for us to reimplement a version of the systemd module (incorrectly too) inside of this one.

2020-04-24 22:56 UTC, anarcat commented on manifests/config.pp
> +        mode    => '0644',
this mode seems unnecessary.

2020-04-24 22:56 UTC, anarcat commented on manifests/daemon.pp
> +        mode    => '0644',
same

2020-04-24 22:56 UTC, anarcat commented on manifests/config.pp
> +        group   => 'root',
same with mode/group. `group = root` will particularly make this fail on platforms where gid 0 is not `root` (but e.g. `wheel`, although arguably those platforms are unlikely to run systemd).

2020-04-24 22:56 UTC, anarcat commented on manifests/daemon.pp
> +      ~> exec { "${name}-systemd-reload":
this seems to duplicate the other daemon-reload.

2020-04-25 07:26 UTC, juliantaylor commented
fair enough, the patch is simple enough to maintain a fork.
maybe when puppet < 6.1 is dropped and this is really just a `sed s/systemd/file/` we can try again.

It is just unfortunate that the systemd module with less features became the standard for you :/ though camptocamp has been improved somewhat in the last 3 years at least.

2020-04-25 07:26 UTC, closed without merging