removed legacy function has_keys
voxpupuli/puppet-prometheus pull request #678
Opened 2023-07-11 07:56 UTC by marszip

#### Pull Request (PR) description

Remove deprecated legacy function has_keys

#### This Pull Request (PR) fixes the following issues
#677

2023-07-11 18:57 UTC, kenyon requested changes

2023-07-11 18:57 UTC, kenyon commented on manifests/config.pp
> +    if ! 'job_name' in $job_definition {
```suggestion
    if ! ('job_name' in $job_definition) {
```

We had a bug caused by this already at https://github.com/voxpupuli/puppet-rsyslog/commit/a146191e6ec44f5a8163fff0887057eb0d08f6d3.

2023-07-12 05:11 UTC, kenyon approved these changes

2023-07-12 18:03 UTC, smortex approved these changes

2023-07-12 18:03 UTC, merged