Update options flag for nginx-prometheus-exporter to new double dash format
voxpupuli/puppet-prometheus pull request #816
Opened 2024-10-24 10:38 UTC by lbdemv

#### Pull Request (PR) description
The nginx exporter logs the following deprecation warning after startup.
```
nginx-prometheus-exporter: the flag format is deprecated and will be removed in a future release, please use the new format: --nginx.scrape-uri
```

This PR intends to fix the deprecated flag format and use the current flag format with double dashes.

#### This Pull Request (PR) fixes the following issues

No issue opened so far.

2024-10-24 12:27 UTC, TheMeier commented
@lbdemv do you know since when the "--" versions are supported?
https://github.com/nginxinc/nginx-prometheus-exporter/releases/tag/v1.0.0 ?

2024-10-24 12:31 UTC, lbdemv commented
Sorry, I didn't actually check that. I just saw it and went on to fix the current warning...

Maybe I can dwell into that later today, if it is important.

2024-10-24 20:27 UTC, lbdemv commented
As i see that, the deprecation change is made in https://github.com/nginxinc/nginx-prometheus-exporter/pull/460 
It was a fix for https://github.com/nginxinc/nginx-prometheus-exporter/issues/447  

The initial issue seem to be the change to kigpin in https://github.com/nginxinc/nginx-prometheus-exporter/pull/420 which was flagged as a breaking change in the mentioned [v1.0.0 changelog](https://github.com/nginxinc/nginx-prometheus-exporter/releases/tag/v1.0.0)

2024-10-28 08:12 UTC, TheMeier commented
I see. The default version in this module is currently 0.11.0 (https://github.com/voxpupuli/puppet-prometheus/blob/master/manifests/nginx_prometheus_exporter.pp#L66) so we need a version comparision here. Also there is a pending MR (https://github.com/voxpupuli/puppet-prometheus/pull/783) to update the  version but that needs some work :(

2024-12-29 19:43 UTC, tuxmea approved these changes

2024-12-29 19:45 UTC, tuxmea requested changes
We still need the version comparison.

2025-01-08 08:41 UTC, lbdemv commented
@tuxmea I'm not sure if you are waiting for me to add anything? Or was this comment more like a memo for yourself?

2025-01-08 09:30 UTC, tuxmea commented
memo

2025-01-12 18:55 UTC, TheMeier commented
@lbdemv we need something like this:

```
if versioncmp($version, '1.0.0') >= 0 {
  $options = "--nginx.scrape-uri '${scrape_uri}' ${extra_options}"
} else {
  $options = "-nginx.scrape-uri '${scrape_uri}' ${extra_options}"
}
```

The tests need to be changed to check both cases. If you don't mind I could update your PR accordingly.

2025-01-12 18:57 UTC, lbdemv commented
I don't mind at all. Go right ahead 😄

2025-08-28 15:29 UTC, TheMeier approved these changes

2025-08-28 15:33 UTC, TheMeier commented
Actually this is obsolete now see https://github.com/voxpupuli/puppet-prometheus/commit/10e98effa22a187b35e35973fcd9072b95bc620e
Thanks for your contribution anyway @lbdemv

2025-08-28 15:33 UTC, closed without merging